services:
  gestion-patients.api:
    image: gestion-patients.api
    container_name: Gestion-Patients.api
    build:
      context: .
      dockerfile: Gestion-Patients.api/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQL-Server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Gk3vLNdhBQf9HMQc
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  ocelot:
    image: ocelot.gateway
    container_name: Ocelot.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Developement
      - ASPNETCORE_HTTP_PORTS=5050
      - ClientAppUrl=http://localhost:4277
      - GestionPatientsApiUrl=https://localhost:8081
      - GestionNotesApiUrl=https://localhost:4041
      - RapportDiabeteApiUrl=http://localhost:3030
    build:
      context: .
      dockerfile: Ocelot-Api.gateway/Dockerfile
    ports:
      - "5000:5050"
    depends_on:
      - gestion-patients.api
  
  angular-app.client:
    image: angular-app.client
    container_name: Angular-App.client
    build:
      context: Angular-App.client
      dockerfile: Dockerfile
    ports:
      - "4277:4277"
  
  gestion-notes.api:
    image:  gestion-notes.api
    container_name: Gestion-Notes.api
    build:
      context: .
      dockerfile: Gestion-Notes.api/Dockerfile
    depends_on:
      - sqlserver
      - mongo

  mongo:
    image: mongo:latest
    container_name: MongoDB
    restart: always
    ports:
      - 27017:27017

  rapport-diabete.api:
    image: rapport-diabete.api
    container_name: Rapport-Diabete.api
    build:
      context: .
      dockerfile: Rapport-Diabete.api/Dockerfile

volumes:
  mysql-data:

