services:
  gestion-patients.api:
    image: gestion-patients.api
    build:
      context: Gestion-Patients.api
      dockerfile: Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQL-Server
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Gk3vLNdhBQf9HMQc"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  ocelot:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Developement"
      - "ClientAppUrl=http://localhost:4277"
      - "GestionPatientsApiUrl=https://localhost:8081"
    build:
      context: Ocelot-Api.gateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - gestion-patients.api
  
  angular-app.client:
    image: angular-app.client
    container_name: Angular-App.client
    build:
      context: Angular-App.client
      dockerfile: Dockerfile
    ports:
      - "4277:4277"
  

volumes:
  mysql-data: